name: Auto Pull Requests

on:
  push:
    branches:
      - Conflomark_Maven

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:

      - name: Revisando CÃ³digo
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: mydemo
      - run: |
          git checkout sonarqube
          git merge Conflomark_Maven
          git push origin sonarqube
